name: Docs
on:
  push:
    branches:
      - main

jobs:
  docs:
    name: Generate Documentation
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup JDK
        uses: actions/setup-java@v1
        with:
          java-version: 11
      - name: Generate Docs
        uses: gradle/gradle-build-action@v2
        with:
          arguments: --stacktrace --info dokkaHtml
      - name: Push docs to gh-pages
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: build/dokka/html
          branch: gh-pages
          git-config-name: GitHub Actions
          git-config-email: actions@github.com
          commit-message: 'chore: generate docs'